### ISSUE TITLE
Fallback for Unicode::UTF8-less operation fails

### ISSUE THREAD

**Issue by eserte** [benkasminbullock/test-cgi-external#10]
See http://matrix.cpantesters.org/?dist=Test-CGI-External%200.10_02 for an overview and http://www.cpantesters.org/cpan/report/9cc87904-8a9c-11e5-b5f1-8461a9884ca8 for a sample fail report --- it seems that falling back to Encode is causing a test failure here.

**Comment by benkasminbullock** [comment]
Thanks for reporting. This is due to use of encode_utf8(@_) with Encode, which uses prototypes so it returns a value 1 due to scalarifying @_ into 1. This is fixed in 3a489b36fd64394e1cdc1eb706e7f5237517c8a8
