### ISSUE TITLE
checks on status 300

### ISSUE THREAD

**Issue by nigelhorne** [benkasminbullock/test-cgi-external#14]
Have a script which sometimes returns status 300.  I'm unsure if that should include a last-modified header.  What's your advice?

**Comment by benkasminbullock** [comment]
Greetings again and thanks for bringing this up.

I have never used this status code. I cannot see why it should not include
a last modified header. That seems reasonable since the result may not have
been modified.

**Comment by nigelhorne** [comment]
OK, thanks, I'll change my script.
